Mutation:
  type: object
  config:
    fields:
      createProduct:
        type: "Product"
        resolve: "@=mutation('create_product', [args])"
        args:
          input:
            type: "ProductInput"

      deleteProduct:
        type: "Product"
        resolve: "@=mutation('delete_product', [args])"
        args:
          input:
            type: "ProductDelete"

      updateProduct:
        type: "Product"
        resolve: "@=mutation('update_product', [args])"
        args:
          input:
            type: "ProductInput"